# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6cc7535210d3dd0eba281bed8deb52a68d949ad661580148530c9fb7025122d2bdbc21fa1045a185b5f9818b2654228b82f12af31ee4c7c08cf9934dad5b6089
  consumer_key: <%= ENV["CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
  token: <%= ENV["TOKEN"] %>
  token_secret: <%= ENV["TOKEN_SECRET"] %>
  consumer_key: <%= ENV["CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
  token: <%= ENV["TOKEN"] %>
  token_secret: <%= ENV["TOKEN_SECRET"] %>

test:
  secret_key_base: 260e19206a47441d087ba3a0a9b777aa7cfaba6fc96ad10038c866b208d4891a3c4406d44b0d903fb9507f83556ba0571c76f9839d1faffeca368886102d3530
  sc_api_key: <%= ENV["sc_api_key"] %>
  gmaps_static_api_key: <%= ENV["GMAPS_STATIC_API_KEY"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sc_api_key: <%= ENV["sc_api_key"] %>
  gmaps_static_api_key: <%= ENV["GMAPS_STATIC_API_KEY"] %>
  consumer_key: <%= ENV["CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
  token: <%= ENV["TOKEN"] %>
  token_secret: <%= ENV["TOKEN_SECRET"] %>
  consumer_key: <%= ENV["CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["CONSUMER_SECRET"] %>
  token: <%= ENV["TOKEN"] %>
  token_secret: <%= ENV["TOKEN_SECRET"] %>
